# This workflow will build a Java project with Maven, deploy/publish built artifacts.
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-maven

name: Publish package to the Maven Central Repository

# When to perform the build action.
on:
  release:
    # When a new release is created in GitHub
    types: [created]

# What will be done as part of this action.
jobs:
  publish:
  
    # Default version - Linux servers.  Shouldn't matter for this project.
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the source code repository.
      - uses: actions/checkout@v4
          
      # Setup the desired Java version in the environment with a Maven local 
      # cache of dependencies (better build performance).  
      # Updates settings.xml to expect an environment variable for server 
      # authentication details.
      - name: Set up Java and Maven Central Repository
        uses: actions/setup-java@v4
        with:
          cache: maven
          java-version: '17'
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      # Incremetn the patch version in the repo, so that all uploads have a unique version
      - name: Increment Patch Version
        env:
          GITHUB_USERNAME: ${{ secrets.GitHubUserName }}
          GITHUB_EMAIL: ${{ secrets.GitHubEmail }}
        run: |
          ./mvn build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion} versions:commit
          git config user.name "${GITHUB_USERNAME}"
          git config user.email "${GITHUB_EMAIL}"
          git commit -m "updated version in pom.xml"
          git push
          
    # Perform the Maven build and site generation locally.  Deploy artifacts to ossrh server.
      - name: Publish package
        run: mvn -P release --batch-mode site deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_PASSPHRASE : ${{ secrets.GPG_PASSPHRASE  }}
